# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apollo
subtitle: Developer
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev-home.apollodata.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Sites
url_projects_react: http://dev.apollodata.com/react
url_projects_reactnative: http://dev.apollodata.com/react-native
url_projects_angular: http://dev.apollodata.com/angular2
url_projects_swift: http://dev.apollodata.com/ios
url_projects_android: http://dev.apollodata.com/android
url_projects_server: http://dev.apollodata.com/tools
url_projects_vanillajs: http://dev.apollodata.com/core
url_community: http://dev.apollodata.com/community
url_blog: https://dev-blog.apollodata.com/
url_slack: http://www.apollodata.com/#slack
url_youtube: https://www.youtube.com/c/ApolloGraphQL


# Social
twitter_username: apollographql
github_username:  apollographql

exclude:
  - node_modules
  - _posts
  - gruntfile.js
  - npm-debug.log
  - src
  - css
  - config
  - scripts
  - package.json
  - README
  - style.less
  - vendor
